[package]
name = "muriel"
version = "0.1.0"
authors = ["ParkSB <parkgds@gmail.com>"]
edition = "2018"

[dependencies]
clap = "2.33.0"
regex = "1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
